name: taming-modern
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # 我们只让 conda 安装它最擅长的东西：
  - python=3.8.5
  - pip=23.3.1      # <-- 固定 pip 版本，避免 metadata 错误
  - cudatoolkit=11.7  # <-- 安装与 3090 兼容的 CUDA 11.7
  - numpy=1.19.2